// Mock assistant catalog derived from `docs/roadmaps/rex_os_quick_actions_inventory.csv`.
//
// Normalization rules applied per the full roadmap §7:
//   - C-8 + C-28  → submittal_sla (mode parameter collapses them)
//   - C-15 + C-60 → monthly_owner_report
//   - All legacy C-* ids preserved as `legacy_aliases` only; slug is
//     the canonical identity going forward.
//
// This is a REPRESENTATIVE subset (~20 actions) covering Wave 1 +
// Session 3 demo coverage. The real catalog will land via Session 1's
// seed-roles-actions migration (`023_seed_roles_actions_automations_aliases.sql`).
// Do NOT hand-edit legacy C-* IDs as primary keys — they are aliases.
//
// Readiness states supported (contract-frozen — see session packet):
//   live | alpha | adapter_pending | writeback_pending | blocked | disabled
//
// Canonical role keys (contract-frozen):
//   VP | PM | GENERAL_SUPER | LEAD_SUPER | ASSISTANT_SUPER | ACCOUNTANT

export const mockCatalog = {
  version: "v1",
  categories: [
    { key: "FINANCIALS", label: "Financials" },
    { key: "SCHEDULING", label: "Scheduling" },
    { key: "PROJECT_MGMT", label: "Project Management" },
    { key: "PROCUREMENT", label: "Procurement" },
    { key: "OPERATIONS", label: "Operations" },
    { key: "EXECUTIVE", label: "Executive" },
    { key: "DIRECTORY", label: "Directory" },
  ],
  actions: [
    // ── Financials ──────────────────────────────────────────────────────
    {
      slug: "budget_variance",
      legacy_aliases: ["C-1"],
      label: "Budget Variance",
      category: "FINANCIALS",
      description: "Budget vs projected cost by cost code",
      params_schema: [
        { name: "PROJECT_ID", type: "project", label: "Project", required: true },
      ],
      risk_tier: "read_only",
      readiness_state: "alpha",
      required_connectors: ["procore"],
      role_visibility: ["VP", "PM", "ACCOUNTANT"],
      enabled: true,
      can_run: true,
    },
    {
      slug: "change_event_sweep",
      legacy_aliases: ["C-2"],
      label: "Change Event Sweep",
      category: "FINANCIALS",
      description: "Open & unpriced CEs across all projects",
      params_schema: [],
      risk_tier: "read_only",
      readiness_state: "adapter_pending",
      required_connectors: ["procore"],
      role_visibility: ["VP", "PM", "ACCOUNTANT"],
      enabled: true,
      can_run: false,
    },
    {
      slug: "pco_summary",
      legacy_aliases: ["C-4"],
      label: "PCO Summary (30 Days)",
      category: "FINANCIALS",
      description: "PCOs created in the last 30 days",
      params_schema: [],
      risk_tier: "read_only",
      readiness_state: "adapter_pending",
      required_connectors: ["procore"],
      role_visibility: ["VP", "PM", "ACCOUNTANT"],
      enabled: true,
      can_run: false,
    },
    {
      slug: "invoice_lien_compliance",
      legacy_aliases: ["C-3"],
      label: "Invoice & Lien Compliance",
      category: "FINANCIALS",
      description: "G703 + lien waiver compliance",
      params_schema: [
        { name: "BILLING_DATE", type: "date", label: "Billing Date", required: true },
      ],
      risk_tier: "read_only",
      readiness_state: "adapter_pending",
      required_connectors: ["procore"],
      role_visibility: ["VP", "PM", "ACCOUNTANT"],
      enabled: true,
      can_run: false,
    },

    // ── Scheduling ──────────────────────────────────────────────────────
    {
      slug: "critical_path_delays",
      legacy_aliases: ["C-10"],
      label: "Critical Path Delays",
      category: "SCHEDULING",
      description: "Critical path tasks behind schedule",
      params_schema: [
        { name: "PROJECT_ID", type: "project", label: "Project", required: true },
      ],
      risk_tier: "read_only",
      readiness_state: "alpha",
      required_connectors: ["procore"],
      role_visibility: ["VP", "PM", "GENERAL_SUPER", "LEAD_SUPER", "ASSISTANT_SUPER"],
      enabled: true,
      can_run: true,
    },
    {
      slug: "two_week_lookahead",
      legacy_aliases: ["C-11"],
      label: "2-Week Look-Ahead",
      category: "SCHEDULING",
      description: "Superintendent-ready look-ahead narrative",
      params_schema: [
        { name: "PROJECT_ID", type: "project", label: "Project", required: true },
        { name: "START_DATE", type: "date", label: "Start", required: false },
        { name: "END_DATE", type: "date", label: "End", required: false },
      ],
      risk_tier: "read_only",
      readiness_state: "alpha",
      required_connectors: ["procore"],
      role_visibility: ["VP", "PM", "GENERAL_SUPER", "LEAD_SUPER", "ASSISTANT_SUPER"],
      enabled: true,
      can_run: true,
    },
    {
      slug: "schedule_variance",
      legacy_aliases: ["C-42"],
      label: "Schedule Variance Report",
      category: "SCHEDULING",
      description: "Tasks behind schedule — flags critical path with negative float",
      params_schema: [],
      risk_tier: "read_only",
      readiness_state: "adapter_pending",
      required_connectors: ["procore"],
      role_visibility: ["VP", "PM", "GENERAL_SUPER", "LEAD_SUPER"],
      enabled: true,
      can_run: false,
    },
    {
      slug: "lookahead_status",
      legacy_aliases: ["C-43"],
      label: "Lookahead Status",
      category: "SCHEDULING",
      description: "Active lookaheads by project — flags gaps in weekly planning",
      params_schema: [],
      risk_tier: "read_only",
      readiness_state: "adapter_pending",
      required_connectors: ["procore"],
      role_visibility: ["VP", "PM", "GENERAL_SUPER", "LEAD_SUPER", "ASSISTANT_SUPER"],
      enabled: true,
      can_run: false,
    },

    // ── Project Management ──────────────────────────────────────────────
    {
      slug: "rfi_aging",
      legacy_aliases: ["C-5", "C-29"],
      label: "RFI Aging",
      category: "PROJECT_MGMT",
      description: "Overdue RFIs across active projects with ball-in-court + cost/sched impact",
      params_schema: [],
      risk_tier: "read_only",
      readiness_state: "alpha",
      required_connectors: ["procore"],
      role_visibility: ["VP", "PM", "GENERAL_SUPER", "LEAD_SUPER", "ASSISTANT_SUPER"],
      enabled: true,
      can_run: true,
    },
    {
      slug: "submittal_sla",
      legacy_aliases: ["C-8", "C-28"],
      label: "Submittal SLA Check",
      category: "PROJECT_MGMT",
      description: "Submittals exceeding internal / A&E review SLA",
      params_schema: [
        { name: "MODE", type: "select", label: "Scope", required: false, options: [
          { value: "internal", label: "Internal review" },
          { value: "ae", label: "A&E review" },
          { value: "both", label: "Both" },
        ] },
      ],
      risk_tier: "read_only",
      readiness_state: "adapter_pending",
      required_connectors: ["procore"],
      role_visibility: ["VP", "PM", "GENERAL_SUPER", "LEAD_SUPER", "ASSISTANT_SUPER"],
      enabled: true,
      can_run: false,
    },
    {
      slug: "daily_log_summary",
      legacy_aliases: ["C-6"],
      label: "Daily Log Summary",
      category: "PROJECT_MGMT",
      description: "Morning field briefing from yesterday's daily logs",
      params_schema: [
        { name: "YESTERDAY_DATE", type: "date", label: "Date", required: false },
      ],
      risk_tier: "read_only",
      readiness_state: "alpha",
      required_connectors: ["procore"],
      role_visibility: ["VP", "PM", "GENERAL_SUPER", "LEAD_SUPER", "ASSISTANT_SUPER"],
      enabled: true,
      can_run: true,
    },
    {
      slug: "punch_list_analysis",
      legacy_aliases: ["C-7"],
      label: "Punch List Analysis",
      category: "PROJECT_MGMT",
      description: "Top deficiency types by trade & location",
      params_schema: [],
      risk_tier: "read_only",
      readiness_state: "adapter_pending",
      required_connectors: ["procore"],
      role_visibility: ["VP", "PM", "GENERAL_SUPER", "LEAD_SUPER", "ASSISTANT_SUPER"],
      enabled: true,
      can_run: false,
    },
    {
      slug: "inspection_pass_fail",
      legacy_aliases: ["C-38"],
      label: "Inspection Pass/Fail",
      category: "PROJECT_MGMT",
      description: "Inspection results — flags failures and overdue items",
      params_schema: [],
      risk_tier: "read_only",
      readiness_state: "adapter_pending",
      required_connectors: ["procore"],
      role_visibility: ["VP", "PM", "GENERAL_SUPER", "LEAD_SUPER"],
      enabled: true,
      can_run: false,
    },

    // ── Directory ───────────────────────────────────────────────────────
    {
      slug: "project_team_roster",
      legacy_aliases: ["C-13"],
      label: "Project Team Roster",
      category: "DIRECTORY",
      description: "Active users with permission flags",
      params_schema: [
        { name: "PROJECT_ID", type: "project", label: "Project", required: true },
      ],
      risk_tier: "read_only",
      readiness_state: "live",
      required_connectors: [],
      role_visibility: ["VP", "PM", "GENERAL_SUPER", "LEAD_SUPER", "ASSISTANT_SUPER", "ACCOUNTANT"],
      enabled: true,
      can_run: true,
    },
    {
      slug: "vendor_compliance",
      legacy_aliases: ["C-14"],
      label: "Vendor Compliance",
      category: "DIRECTORY",
      description: "Insurance status RED/YELLOW/GREEN",
      params_schema: [],
      risk_tier: "read_only",
      readiness_state: "live",
      required_connectors: [],
      role_visibility: ["VP", "PM", "ACCOUNTANT"],
      enabled: true,
      can_run: true,
    },

    // ── Procurement ─────────────────────────────────────────────────────
    {
      slug: "procurement_readiness",
      legacy_aliases: ["C-52"],
      label: "Procurement Readiness",
      category: "PROCUREMENT",
      description: "Upcoming task procurement status — GREEN/YELLOW/RED",
      params_schema: [
        { name: "PROJECT_ID", type: "project", label: "Project", required: true },
        { name: "WEEKS", type: "text", label: "Weeks ahead", required: false },
      ],
      risk_tier: "read_only",
      readiness_state: "blocked",
      required_connectors: ["procore"],
      role_visibility: ["VP", "PM", "GENERAL_SUPER", "LEAD_SUPER"],
      enabled: true,
      can_run: false,
    },

    // ── Operations ──────────────────────────────────────────────────────
    {
      slug: "morning_briefing",
      legacy_aliases: ["C-22"],
      label: "Morning Briefing",
      category: "OPERATIONS",
      description: "On-demand briefing with all alerts",
      params_schema: [],
      risk_tier: "read_only",
      readiness_state: "live",
      required_connectors: [],
      role_visibility: ["VP", "PM", "GENERAL_SUPER", "LEAD_SUPER", "ASSISTANT_SUPER", "ACCOUNTANT"],
      enabled: true,
      can_run: true,
    },
    {
      slug: "my_day_briefing",
      legacy_aliases: ["C-76"],
      label: "My Day Briefing",
      category: "OPERATIONS",
      description: "Personalized daily briefing: alerts, tasks, meetings, weather, top priorities",
      params_schema: [],
      risk_tier: "read_only",
      readiness_state: "alpha",
      required_connectors: [],
      role_visibility: ["VP", "PM", "GENERAL_SUPER", "LEAD_SUPER", "ASSISTANT_SUPER", "ACCOUNTANT"],
      enabled: true,
      can_run: true,
    },
    {
      slug: "closeout_readiness",
      legacy_aliases: ["C-24"],
      label: "Closeout Readiness",
      category: "OPERATIONS",
      description: "Closeout completeness + blocking items",
      params_schema: [
        { name: "PROJECT_ID", type: "project", label: "Project", required: true },
      ],
      risk_tier: "read_only",
      readiness_state: "live",
      required_connectors: [],
      role_visibility: ["VP", "PM", "GENERAL_SUPER", "LEAD_SUPER"],
      enabled: true,
      can_run: true,
    },
    {
      slug: "command_mode",
      legacy_aliases: ["C-68"],
      label: "Command Mode",
      category: "OPERATIONS",
      description: "Type what you want done in plain English — Rex parses it into actions",
      params_schema: [],
      risk_tier: "mixed",
      readiness_state: "writeback_pending",
      required_connectors: ["procore"],
      role_visibility: ["VP", "PM", "GENERAL_SUPER", "LEAD_SUPER", "ASSISTANT_SUPER", "ACCOUNTANT"],
      enabled: true,
      can_run: false,
    },

    // ── Executive ───────────────────────────────────────────────────────
    {
      slug: "monthly_owner_report",
      legacy_aliases: ["C-15", "C-60"],
      label: "Monthly Owner Report",
      category: "EXECUTIVE",
      description: "Formal monthly owner/lender report — budget, schedule, issues, photos",
      params_schema: [
        { name: "PROJECT_ID", type: "project", label: "Project", required: true },
        { name: "REPORT_MONTH", type: "month", label: "Report Month", required: true },
      ],
      risk_tier: "read_only",
      readiness_state: "adapter_pending",
      required_connectors: ["procore"],
      role_visibility: ["VP", "PM"],
      enabled: true,
      can_run: false,
    },
    {
      slug: "portfolio_snapshot",
      legacy_aliases: ["C-69"],
      label: "Portfolio Snapshot",
      category: "EXECUTIVE",
      description: "Cross-project portfolio view: budget health, schedule, open items, risk ratings",
      params_schema: [],
      risk_tier: "read_only",
      readiness_state: "alpha",
      required_connectors: [],
      role_visibility: ["VP"],
      enabled: true,
      can_run: true,
    },
  ],
};
